#!/usr/bin/env bash

[ -z "$1" ] && exit
[ -z "$2" ] && exit

user=$JIRA_USER
domain=$JIRA_DOMAIN
token=$JIRA_API_TOKEN
issue=$1
estimacion=$2

curl -X PUT "https://$domain/rest/api/2/issue/$issue" -u "$user:$token"  -H "Content-Type: application/json" --data "{\"fields\": {\"timetracking\": {\"originalEstimate\": \"$estimacion\"}, \"parent\":{\"key\":null}}}"
