#!/usr/bin/env bash

ms_path="$MS_REPOS_PATH"
rest_path="$REST_REPO_PATH"
envs=("dev" "int" "cert" "prod")
modes=("swagger.-- Generate swagger for ms" 
  "internal.-- Generate internal (OpenShift) postman collection for all ms"
  "external.-- Generate external (3scale) postman collection for all ms"
)

script=$rest_path/main.js

mode=$(printf "\n" | printf '%s\n' "${modes[@]}" | column -t -s '.' -o '      ' | fzf-tmux -w 100% -h 100% --prompt="Choose mode: " --info=inline --layout=reverse | awk '{print $1}')
[ -z "$mode" ] && exit

if [ $mode = "swagger" ]; then
repo=$(find $ms_path -mindepth 1 -maxdepth 1 -type d | fzf-tmux -w 100% -h 100% --info=inline --layout=reverse)
[ -z "$repo" ] && exit
ms=$(basename "$repo" | tr . _)
node $script swagger $ms
mv $rest_path/specification.yaml $repo/swagger/docs
exit
fi

env=$(printf "\n" | printf '%s\n' "${envs[@]}" | fzf-tmux -w 100% -h 100% --prompt="Choose env: " --info=inline --layout=reverse)
[ -z "$env" ] && exit

node $script $mode $env
