#!/usr/bin/env bash

argocd_path=$ARGOCD_REPO_PATH
glab_user=$GITLAB_USER
ms_repos_path=$MS_REPOS_PATH
mf_repos_path=$MF_REPOS_PATH

envs=("dev" "int" "cert" "prod")

path=$(find $ms_repos_path $mf_repos_path -mindepth 1 -maxdepth 1 -type d | fzf-tmux -w 100% -h 100% --info=inline --layout=reverse)
[ -z "$path" ] && exit

name=$(basename "$path")
type=$(echo "$name" | cut -c1-3)

if [ $type != "app" ]
then
  name="movistarempresas-$name"
fi

env=$(printf '%s\n' "${envs[@]}" | fzf-tmux -w 100% -h 100% --prompt="Pick env: " --info=inline --layout=reverse)
[ -z "$env" ] && exit
version=$(printf "\n" | fzf-tmux -w 100% -h 100% --print-query --prompt="Enter version:" --info=inline --layout=reverse|awk '{printf $1}')
[ -z "$version" ] && exit

title="$name-$env"
namespace="movistar-empresas-$env"

if [ "$env" == "prod" ]
then 
namespace="movistar-empresas"
fi

description=""
read -r -d '' description <<- EOM
platform:openshift
project:empresas
namespace:$namespace
deployment:$name
version:v$version
EOM

cd "$argocd_path" || exit

glab issue create -y --no-editor -a "$glab_user" --title "$title" --description "$description"
