#!/usr/bin/env bash

branch="$1"
path="$2"
glab_user=$GITLAB_USER

[ -z "$branch" ] && exit

cd "$path" || exit  
glab mr create -b "$branch" -a "$glab_user" --no-editor -y --fill-commit-body --fill
end=$((SECONDS+40))
while [ $SECONDS -lt $end ]; do
  for var in / - \\ \|; do echo -en "\r$var Building merge request";sleep .1; done 
done
glab mr merge -d -y || (echo "Retrying merge..." && sleep 20 && glab mr merge -d -y)
