#!/usr/bin/env bash

glab_user=$GITLAB_USER
oc_user=$OC_USER
library=$1
key="dependencies" # dependencies | devDependencies
mf_path=$MF_REPOS_PATH
source_branch="feature/bump-kenos"

name=$4
[ -z "$name" ] && exit

version=$2
[ -z "$version" ] && exit

message="feat: bump $library to $version"

project=$3
[ -z "$project" ] && exit

oc project "$project"
oc login -u "$oc_user" -p "$(pass show oc/pass)"

target_branch="develop"

if [ "$project" == "movistar-empresas-cert" ]
then
  source_branch="bugfix/bump-kenos"
  target_branch="release"
fi

merge_branch=$target_branch

if [ "$project" == "movistar-empresas" ]
then
  source_branch="despliegue/prod"
  target_branch="release"
  merge_branch="master"
fi

path=$mf_path/$name
package="$path/package.json"
echo "Updating $library to $version in $path"
cd "$path" || exit
stashed=$(git stash list | wc -l)
git stash
stashed2=$(git stash list | wc -l)

if [ "$project" == "movistar-empresas" ]
then
  git switch $merge_branch
  git pull
fi

git switch $target_branch
git pull

query=".$key.\"$library\""
current_version=$(cat "$package" | jq "$query" | sed -e 's/\"//g')

if [ "$current_version" != "$version" ]
then
  git branch -D $source_branch
  git branch $source_branch
  git switch -
  git switch $source_branch

  npm install -E "$library@$version"
  npm run build

  git add "$package"
  git commit -m "$message"
  glab mr create -b $merge_branch -a "$glab_user" --no-editor -y --fill-commit-body --fill

  if [ "$project" != "movistar-empresas" ]
  then
  end=$((SECONDS+40))
  while [ $SECONDS -lt $end ]; do
    for var in / - \\ \|; do echo -en "\r$var Building merge request";sleep .1; done 
  done
  glab mr merge -d -y || (echo "Retrying merge..." && sleep 20 && glab mr merge -d -y)
  fi

else
  echo "Skipping $path: $library version is already $current_version"
fi
git switch -

if [ "$stashed" != "$stashed2" ]
then
  git stash pop 
fi
