#!/usr/bin/env bash

user=$JIRA_USER
domain=$JIRA_DOMAIN
token=$JIRA_API_TOKEN

actions=(
  "Create.-- Create new issue"
  "View.-- View issue detail" 
  "Add.-- Add issue to current sprint"
  "Assign.-- Assign issue to someone else"
  "Subtask.-- Create new subtask"
  "Time.-- Edit or log time"
  "Move.-- Transition issue"
  "Comment.-- New comment on issue"
  "Link.-- Link issue to parent"
  "Unlink.-- Unlink issue from parent"
  "Delete.-- Delete issue"
  "Edit.-- Edit issue"
  "Open.-- Open issue in browser"
  "Start.-- Start issue"
)


action=$(printf '%s\n' "${actions[@]}" | column -t -s '.' -o '      ' | $fzf_client --prompt="Choose command: ")
[ -z "$action" ] && exit
command=$(echo "$action" | awk '{print $1}')

if [ "$command" == "Create" ]
then
jira issue create -a "$user" -lECR-Replacement -lECR-Raplacement  -PECR-10029 
created_issue=$(jira issue list --plain --no-headers | head -n 1 | awk '{print $2}')

estimacion=$(echo "" | $fzf_client --prompt="Estimacion: " --print-query)
[ -z "$estimacion" ] && exit
curl -X PUT "https://$domain/rest/api/2/issue/$created_issue" -u "$user:$token"  -H "Content-Type: application/json" --data "{\"fields\": {\"timetracking\": {\"originalEstimate\": \"$estimacion\"}, \"parent\":{\"key\":null}}}"
exit
fi

extra_flags=
if [ "$command" == "Subtask" ]
then
  extra_flags=-t~Sub-task
fi

issue=$(jira issue list $extra_flags -s~Finalizado -s~Cancelado -lECR-Replacement -lECR-Raplacement --no-headers --plain | $fzf_client --prompt="Select isssue: " --no-sort | awk '{print $2}')
[ -z "$issue" ] && exit

if [ "$command" == "Assign" ]
then
users=$(curl -X GET "https://$domain/rest/api/3/user/assignable/search?project=ECR&maxResults=1000" -u "$user:$token" | jq '.[].displayName')
user=$(echo "$users" | $fzf_client --prompt="Select user: ")
[ -z "$user" ] && exit
jira issue assign "$issue" $user
exit 
fi

if [ "$command" == "Add" ]
then
sprint=$(jira sprint list --plain --no-headers --table --columns=ID,STATE | head -n1 )
sprint_id=$(echo "$sprint" | awk '{print $1}')
sprint_state=$(echo "$sprint" | awk '{print $2}')
if [ "$sprint_state" == "active"  ]
then 
  jira sprint add "$sprint_id" "$issue"
else
  echo "No sprint is active"
fi
exit 
fi

if [ "$command" == "Comment" ]; then
jira issue comment add "$issue"
exit
fi

if [ "$command" == "View" ]; then
jira issue view "$issue"
exit
fi

if [ "$command" == "Edit" ]; then
  jira issue edit "$issue"
exit
fi

if [ "$command" == "Move" ]; then
jira issue move "$issue"
exit
fi

if [ "$command" == "Open" ]; then
jira open "$issue" | xargs -r $BROWSER
exit
fi

if [ "$command" == "Delete" ]; then
jira issue move "$issue" "Cancelado"
exit
fi

if [ "$command" == "Subtask" ]; then
jira issue create -a "$user" -lECR-Replacement -lECR-Raplacement -tSub-task -P"$issue"

estimacion=$(echo "" | $fzf_client --prompt="Estimacion: " --print-query)
[ -z "$estimacion" ] && exit

created_issue=$(jira issue list --plain --no-headers | head -n 1 | awk '{print $2}')
curl -X PUT "https://$domain/rest/api/2/issue/$created_issue" -u "$user:$token"  -H "Content-Type: application/json" --data "{\"fields\": {\"timetracking\": {\"originalEstimate\": \"$estimacion\"}}}"
exit
fi

if [ "$command" == "Time" ]; then
submenu=("Edit.-- Edit original estimate" 
  "Log.-- Log time spent")

selected=$(printf '%s\n' "${submenu[@]}" | column -t -s '.' -o '      ' | $fzf_client --prompt="Choose command: ")
[ -z "$selected" ] && exit
subcommand=$(echo "$selected" | awk '{print $1}')

estimacion=$(echo "" | $fzf_client --prompt="Estimacion: " --print-query)
[ -z "$estimacion" ] && exit

if [ "$subcommand" == "Log" ]; then
  jira issue worklog add "$issue" "$estimacion"
  exit
fi

if [ "$subcommand" == "Edit" ]; then
curl -X PUT "https://$domain/rest/api/2/issue/$issue" -u "$user:$token"  -H "Content-Type: application/json" --data "{\"fields\": {\"timetracking\": {\"originalEstimate\": \"$estimacion\"}}}"
exit
fi

fi

clock() {
  while :;do 
   end_time=$(date +%s)
   duration=$((end_time - $1 - $2))
   echo -en "\rElapsed time: $(date -d@$duration -u +%H:%M:%S)"
   sleep .8
  done
}

if [ $command == "Start" ]; then
  jira issue move "$issue" "Iniciar"
  start_time=$(date +%s)
  paused_time=0
  while true; do
    clear
    echo "Working on issue: $issue"
    echo "$(jira issue view "$issue" --plain | grep -v '^[[:space:]]*$')"
    clock "$start_time" $paused_time &
    pid=$!
    echo "Press 'p' to pause or 'f' to finish."
    read -s -n1 key
    if [[ $key == 'p' ]]; then
      kill $pid
      pause_time=$(date +%s)
      echo -e "\nIssue paused."
      read -p "¿Log time? (y/n): " record_time
      if [[ $record_time == 'y' ]]; then
        resume_time=$(date +%s)
        pause_duration=$((resume_time - pause_time))
        paused_time=$((paused_time + pause_duration))
        duration=$(((pause_time - start_time - paused_time)/60))
        echo "Logging $duration minutes"
         jira issue worklog add "$issue" "$duration"
        break
      fi
      resume_time=$(date +%s)
      pause_duration=$((resume_time - pause_time))
      paused_time=$((paused_time + pause_duration))
    elif [[ $key == 'f' ]]; then
      kill $pid
      end_time=$(date +%s)
      duration=$(((end_time - start_time - paused_time)/60))
      echo -e "\nIssue finished."
      read -p "¿Log time? (y/n): " record_time
      if [[ $record_time == 'y' ]]; then
         jira issue worklog add "$issue" "$duration"
        echo "Logging $duration minutes"
        read -p "¿Move task to finished? (y/n): " finish 
        if [[ $finish == 'y' ]]; then
           jira issue move "$issue" "Finalizado"
        fi
      fi
      break
    fi
  done
  exit
fi

issue2=$(jira issue list -sPendiente -lECR-Replacement -lECR-Raplacement --no-headers --plain | $fzf_client --prompt="Select isssue: " --no-sort | awk '{print $2}')
[ -z "$issue2" ] && exit

if [ "$command" == "Link" ]; then
jira issue link "$issue" "$issue2"
exit
fi

if [ "$command" == "Unlink" ]; then
jira issue unlink "$issue" "$issue2"
exit
fi
