#!/usr/bin/env bash

full_path=$1
service_name=$(basename "$(dirname "$full_path")")
echo "$service_name"
file_name=$(basename "$full_path")

env=${file_name#values-movistar-empresas-*}
env=$(echo "$env" | sed -e 's/\..*//')

type=$2

modulo="MIMOVISTAREMPRESAS"
tipo="FCD"
clave_jira="ECR"
masivo_critico="NO"
issue_jira="NO_INFORMADO"

route_enabled="true"

limit_cpu="40m"
limit_mem="128Mi"
req_cpu="15m"
req_mem="64Mi"

autoscaling="false"
min_replicas="1"
max_replicas="3"

readiness_probe="true"
elasticsearch=1

elk_logs="on"
elk_logs_debug="off"
stdout_logs="on"

lproduct="mimovistarempresas"
lenvironment="$env"


if [ $type == "dao" ]
then
tipo="DAO"
fi

if [ $type == "int" ]
then
tipo="INT"
fi

if [ $env == "cert" ]
then
autoscaling="true"
min_replicas="3"
max_replicas="6"
stdout_logs="off"
limit_cpu="100m"
limit_mem="256Mi"
req_cpu="30m"
req_mem="256Mi"
fi

if [ $type == "app" ]
then
tipo="MICROFRONTEND"
route_enabled="false"
readiness_probe="false"
elasticsearch=0
# limit_cpu="100m"
# limit_mem="256Mi"
# req_cpu="30m"
# req_mem="256Mi"
fi

file_content=$(cat $full_path | yq)

replace(){
  key=$1
  value=$2
  arg=--argjson
  if [ "$3" == "string" ]
  then
    arg=--arg
  fi
  file_content=$(echo "$file_content" | jq $arg a "$value" ".\"helm-chart-master\".$key = \$a")
}

replace "dynatrace.modulo" $modulo "string"
replace "dynatrace.tipo" $tipo "string"
replace "dynatrace.clave_jira" $clave_jira "string"
replace "dynatrace.masivo_critico" $masivo_critico "string"
replace "dynatrace.issue_jira" $issue_jira "string"

replace "route.enabled" $route_enabled

if [ $service_name != "app-shell-oc" ]
then
replace "resources.limits.cpu" $limit_cpu "string"
replace "resources.limits.memory" $limit_mem "string"
replace "resources.requests.cpu" $req_cpu "string"
replace "resources.requests.memory" $req_mem "string"
fi

replace "autoscaling.enabled" $autoscaling
replace "autoscaling.minReplicas" $min_replicas
replace "autoscaling.maxReplicas" $max_replicas

replace "readinessProbe.enabled" $readiness_probe

if [ $elasticsearch == 1 ]
then 
  has_elastic_search=$(echo $file_content | jq '."helm-chart-master".secrets | to_entries | .[] | select(.value=="elasticsearch")')
if [ "$has_elastic_search" == "" ]
then
  last_secret=$(echo $file_content | jq '."helm-chart-master".secrets | to_entries | sort_by(.key)| reverse| .[0].key')
  last_secret=$(echo "$last_secret" | sed -e 's/"//g')
  last_secret_index=${last_secret#secret*}
  next_index=$((last_secret_index + 1))
  replace "secrets.secret$next_index" "elasticsearch" "string"
fi
fi

replace "configmapENV.ELK_LOGS" $elk_logs "string"
replace "configmapENV.ELK_LOGS_DEBUG" $elk_logs_debug "string"
replace "configmapENV.STDOUT_LOGS" $stdout_logs "string"

replace "labels.lproduct" $lproduct "string"
replace "labels.lenvironment" $lenvironment "string"

echo "$file_content" | yq -y > $full_path
