#!/usr/bin/env bash

glab_user=$GITLAB_USER
deploy_repos_path=$OC_REPOS_PATH
scripts_repo=$SCRIPTS_REPO_PATH
env=$1
path=$2
version=$3

# TODO: Support for updating multiple envs 
# selected_envs=($selected)

# TODO: This is not entirely correct, not all 
# ms use fcd-  int-  
# relying on path is also not ideal since users can have
# arbitrary names for directories, should probably
# rely on yaml fullNameOverride or something ? 
type=$(basename "$path"| cut -c1-3)

cd "$path" || exit
stashed=$(git stash list | wc -l)
git stash
stashed2=$(git stash list | wc -l)

git switch master
git pull

git branch -D feature/despliegue 
git switch -c feature/despliegue


# TODO: Support for updating multiple envs 
# for env in "${selected_envs[@]}"
# do
  file_name="values-movistar-empresas-$env.yaml"
  $scripts_repo/dep-yaml $path/$file_name $type 
  sed -i "s/tag: .*/tag: $version/" $path/$file_name
  git add $file_name
# done

git commit -m "$version"

branch="master"
glab mr create -b $branch -a $glab_user --no-editor -y --fill-commit-body --fill
end=$((SECONDS+40))
while [ $SECONDS -lt $end ]; do
  for var in / - \\ \|; do echo -en "\r$var Building merge request";sleep .1; done 
done
glab mr merge -d -y $mr || (echo "Retrying merge..." && sleep 20 && glab mr merge -d -y $mr)

if [ "$stashed" != "$stashed2" ]
then
  git stash pop 
fi

$SCRIPTS_REPO_PATH/pipes
