#!/usr/bin/env bash

download_logs_path=$LOGS_PATH

[ -z "$1" ] && exit 1
[ -z "$2" ] && exit 1
[ -z "$3" ] && exit 1

pod_name=$1
pods=$2
project=$3

temp=${pod_name%-*}
app_name=${temp%-*}

date=""
printf -v date '%(%Y-%m-%d)T' -1
time=$(date +"%T")
if [ ! -d "$download_logs_path/$project/$date" ]; then 
  mkdir -p "$download_logs_path/$project/$date"
fi

tmp=$(echo "$pods" | grep $app_name)

arr=($tmp)

for p in "${arr[@]}"
do
   echo $p
  filename="$download_logs_path/$project/$date/[$time]_${p}"
  touch "$filename"
  $OC logs -f=false pod/${p} >> "$filename"
done
