#!/usr/bin/env bash

ms_path=$MS_REPOS_PATH
envs_external_script=$SCRIPTS_REPO_PATH/envs-external
oc_user=$OC_USER

tmp_file=/tmp/resource
projects=("movistar-empresas-dev" "movistar-empresas-int" "movistar-empresas-cert" "movistar-empresas")
actions=("Create" "Copy" "Edit" "Delete")
resources=("Configmap" "Secret")

project=$(printf "\n" | printf '%s\n' "${projects[@]}" | fzf-tmux -w 100% -h 100% --prompt="Choose project: " --info=inline --layout=reverse)
[ -z "$project" ] && exit

oc project "$project"
oc login -u "$oc_user" -p "$(pass show oc/pass)"

action=$(printf "\n" | printf '%s\n' "${actions[@]}" | fzf-tmux -w 100% -h 100% --prompt="Choose command: " --info=inline --layout=reverse)
[ -z "$action" ] && exit

resource=$(printf "\n" | printf '%s\n' "${resources[@]}" | fzf-tmux -w 100% -h 100% --prompt="Choose resource: " --info=inline --layout=reverse)
[ -z "$resource" ] && exit

edit_arg="secret"
if [ $resource == "Configmap" ]
then
  edit_arg="configmap"
fi

if [ $action == "Edit" ]
then
  res=$(oc get $edit_arg | sed 1d | fzf-tmux -w 100% -h 100% --prompt="Choose config map: " --info=inline --layout=reverse | awk '{printf $1}')
  [ -z "$res" ] && exit
  echo -n "edit $edit_arg $res" | xargs -d " " oc
fi

if [ $action == "Delete" ]
then
  res=$(oc get $edit_arg | sed 1d | fzf-tmux -w 100% -h 100% --color=prompt:9 --color=pointer:9 --prompt="DELETING!!" --info=inline --layout=reverse | awk '{printf $1}')
  [ -z "$res" ] && exit
  echo -n "delete $edit_arg $res" | xargs -d " " oc
fi

