#!/usr/bin/env bash

if [ $# != 1 ]
then
  echo "Usage: external-envs <file>"
  exit 1
fi

sed -i 's/.movistar-empresas/-movistar-empresas/g' $1 
sed -i 's/.svc.cluster.local:8080/.apps.ocpnp.cuyorh.tcloud.ar/g' $1 
