#!/usr/bin/env bash

projects=("ci-paas" "cd-paas" "3scale-automation")
oc_user=$OC_USER

project=$1

if [[ -z $1 ]] then
  project=$(printf "\n" | printf '%s\n' "${projects[@]}" | fzf-tmux -w 100% -h 100% --prompt="Choose project: " --info=inline --layout=reverse)
  [ -z "$project" ] && exit
fi

oc project $project
oc login -u $oc_user -p $(pass show oc/pass)

pipeline=$(tkn pipelinerun list | sed 1d | fzf-tmux -w 100% -h 100% --prompt="Choose pipeline: " --info=inline --layout=reverse | awk '{printf $1}')
[ -z "$pipeline" ] && exit

clear
tmux clear-history

tkn pipelinerun logs $pipeline -f
